name: appcon_ai_lab
description: Pre-event Flutter and Firebase AI Logic integration practice.
publish_to: none
version: 0.1.0+1
environment:
  sdk: '>=3.6.0 <4.0.0'
dependencies:
  flutter:
    sdk: flutter
  firebase_core: 4.15.0
  firebase_ai: 4.0.0
  firebase_app_check: 0.4.8
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: 6.0.0
flutter:
  uses-material-design: true
