import 'dart:async';

import 'package:firebase_ai/firebase_ai.dart';
import 'package:firebase_app_check/firebase_app_check.dart';
import 'package:firebase_core/firebase_core.dart';
import 'package:flutter/foundation.dart';
import 'package:flutter/material.dart';

const modelId = String.fromEnvironment('AI_MODEL');

Future<void> main() async {
  WidgetsFlutterBinding.ensureInitialized();
  var configured = false;
  try {
    // Android's default options are generated by `flutterfire configure`.
    await Firebase.initializeApp();
    await FirebaseAppCheck.instance.activate(
      providerAndroid: kDebugMode
          ? const AndroidDebugProvider()
          : const AndroidPlayIntegrityProvider(),
    );
    configured = true;
  } catch (_) {
    // Setup failures are shown honestly; no generated or cached fake result.
  }
  runApp(AiLab(configured: configured));
}

class AiLab extends StatelessWidget {
  const AiLab({super.key, required this.configured});
  final bool configured;

  @override
  Widget build(BuildContext context) => MaterialApp(
        debugShowCheckedModeBanner: false,
        title: 'AppCon AI Lab',
        theme: ThemeData(
          useMaterial3: true,
          colorScheme: ColorScheme.fromSeed(
            seedColor: const Color(0xFF5C43C7),
          ),
          scaffoldBackgroundColor: const Color(0xFFF7F5FC),
          inputDecorationTheme: const InputDecorationTheme(
            filled: true,
            fillColor: Colors.white,
            border: OutlineInputBorder(),
          ),
        ),
        home: LabScreen(configured: configured),
      );
}

class LabScreen extends StatefulWidget {
  const LabScreen({super.key, required this.configured});
  final bool configured;

  @override
  State<LabScreen> createState() => _LabScreenState();
}

class _LabScreenState extends State<LabScreen> {
  final input = TextEditingController();
  bool busy = false;
  String? result;
  String? error;
  int? elapsedMs;

  @override
  void dispose() {
    input.dispose();
    super.dispose();
  }

  Future<void> generate() async {
    if (busy || !widget.configured || modelId.isEmpty) return;
    final text = input.text.trim();
    if (text.isEmpty) {
      setState(() => error = 'Enter a harmless practice prompt first.');
      return;
    }
    if (text.length > 2000) {
      setState(
          () => error = 'Keep this practice prompt under 2,000 characters.');
      return;
    }
    setState(() {
      busy = true;
      error = null;
      result = null;
      elapsedMs = null;
    });
    final timer = Stopwatch()..start();
    try {
      final model = FirebaseAI.googleAI().generativeModel(model: modelId);
      final response = await model.generateContent(
          [Content.text(text)]).timeout(const Duration(seconds: 30));
      final answer = response.text?.trim();
      if (answer == null || answer.isEmpty) {
        throw StateError('No usable response');
      }
      if (!mounted) return;
      setState(() {
        result = answer;
        elapsedMs = timer.elapsedMilliseconds;
      });
    } on TimeoutException {
      if (!mounted) return;
      setState(() {
        error = 'The request timed out. Your input is still here. Check your '
            'connection before retrying; the previous request may still finish '
            'at the provider.';
      });
    } catch (_) {
      if (!mounted) return;
      setState(() {
        error =
            'No usable AI response. Check network access, model availability, '
            'project quota and App Check registration, then retry.';
      });
    } finally {
      timer.stop();
      if (mounted) setState(() => busy = false);
    }
  }

  @override
  Widget build(BuildContext context) {
    final ready = widget.configured && modelId.isNotEmpty;
    return Scaffold(
      appBar: AppBar(title: const Text('AppCon • AI Lab')),
      body: SafeArea(
        child: Center(
          child: ConstrainedBox(
            constraints: const BoxConstraints(maxWidth: 640),
            child: ListView(
              padding: const EdgeInsets.all(24),
              children: [
                Text('Learn the connection.',
                    style: Theme.of(context).textTheme.headlineMedium),
                const SizedBox(height: 8),
                const Text('Flutter → Firebase AI Logic → Gemini.\n'
                    'Practice workspace • not the competition entry.'),
                const SizedBox(height: 24),
                Card(
                  child: Padding(
                    padding: const EdgeInsets.all(16),
                    child: Text(!widget.configured
                        ? 'Setup needed: configure Firebase for Android and '
                            'register App Check. See docs/FLUTTER_AI.md.'
                        : modelId.isEmpty
                            ? 'Choose an enabled model with '
                                '--dart-define=AI_MODEL=MODEL_ID.'
                            : 'Configuration loaded • model: $modelId. '
                                'A successful response verifies connectivity.'),
                  ),
                ),
                const SizedBox(height: 16),
                TextField(
                  controller: input,
                  minLines: 4,
                  maxLines: 8,
                  maxLength: 2000,
                  enabled: !busy,
                  decoration: const InputDecoration(
                    labelText: 'Practice prompt',
                    hintText:
                        'Explain how solar panels work in three sentences.',
                    helperText:
                        'Use non-sensitive text. Input goes to a hosted model.',
                    helperMaxLines: 2,
                  ),
                ),
                const SizedBox(height: 16),
                FilledButton.icon(
                  onPressed: ready && !busy ? generate : null,
                  icon: busy
                      ? const SizedBox(
                          width: 18,
                          height: 18,
                          child: CircularProgressIndicator(strokeWidth: 2),
                        )
                      : const Icon(Icons.auto_awesome),
                  label: Padding(
                    padding: const EdgeInsets.all(14),
                    child:
                        Text(busy ? 'Requesting AI…' : 'Send real AI request'),
                  ),
                ),
                if (error != null) ...[
                  const SizedBox(height: 16),
                  Semantics(
                    liveRegion: true,
                    child: Text(error!,
                        style: TextStyle(
                            color: Theme.of(context).colorScheme.error)),
                  ),
                ],
                if (result != null) ...[
                  const SizedBox(height: 24),
                  Text('Model response',
                      style: Theme.of(context).textTheme.titleLarge),
                  Text(
                      '$elapsedMs ms • review generated content before using it'),
                  const SizedBox(height: 12),
                  Card(
                    child: Padding(
                      padding: const EdgeInsets.all(20),
                      child: SelectableText(result!),
                    ),
                  ),
                ],
              ],
            ),
          ),
        ),
      ),
    );
  }
}
